// <auto-generated />
namespace PizzaProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Auth21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Auth21));
        
        string IMigrationMetadata.Id
        {
            get { return "202001260119550_Auth21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
